name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version to deploy"
        required: true

permissions:
  contents: read
  packages: read
  issues: write

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Yandex Container Registry
        run: |
          echo "${{ secrets.YCR_TOKEN }}" | docker login \
            --username "${{ secrets.YCR_USER }}" \
            --password-stdin cr.yandex

      - name: Check Docker image exists
        run: |
          echo "Checking image $REGISTRY:${VERSION}_latest"
          docker manifest inspect "$REGISTRY:${VERSION}_latest"

      - name: Deploy to prod via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            REGISTRY="${{ env.REGISTRY }}"
            VERSION="${{ env.VERSION }}"

            echo "${{ secrets.YCR_TOKEN }}" | docker login \
              --username "${{ secrets.YCR_USER }}" \
              --password-stdin cr.yandex

            docker pull "$REGISTRY:${VERSION}_latest"

            docker stop shri-infra-hw || true
            docker rm   shri-infra-hw || true

            docker run -d \
              --name shri-infra-hw \
              -p 3000:3000 \
              "$REGISTRY:${VERSION}_latest"

      - name: Find Release Issue number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=$(gh issue list \
            --state all \
            --search "Release $VERSION deployed" \
            --json number \
            --jq '.[0].number')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Comment on Release Issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          body: |
            Деплой версии ${{ env.VERSION }} на прод завершён  
            Дата: $(date +'%Y-%m-%d')  
            Кто: ${{ github.actor }}
